services:
  app:
    build:
      context: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    depends_on:
      - db
    ports:
      - "5173:5173"
    environment:
      - VITE_HTTPS=true

  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
